name: bgsms
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_background_service: ^5.0.7
  flutter_background_service_android: ^6.2.4
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.1
  shared_preferences: ^2.3.1
  readsms:
    path: ./plugins/readsms

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
